# Basic Site Settings
locale: "en-US"
title: "Trung-Thai DO / PhD Student"
name: "Trung-Thai DO"
description: "PhD Student at the University of Toulouse, focusing on photoacoustic imaging, image processing, inverse problems, and deep learning."
url: "https://dotrungthai2001.github.io"
repository: "dotrungthai2001/dotrungthai2001.github.io"

# Site Author (for the sidebar)
author:
  avatar: "profile.png" # Make sure this file is in your /images/ folder
  name: "Trung-Thai DO"
  bio: PhD student at the University of Toulouse, working on reconstruction methods for 3D photoacoustic imaging.
  location: "Toulouse, France & Singapore"
  email: "trungthai1771@gmail.com"
  googlescholar: "https://scholar.google.com/citations?user=_srBckcAAAAJ&hl=en" 
  orcid: "https://orcid.org/0009-0004-0528-0504"
  github: "dotrungthai2001"
  linkedin: "trung-thai-do" # Your LinkedIn username/slug

# Reading Files
include:
  - _pages
  - files
exclude:
  - Dockerfile
  - Gemfile
  - LICENSE
  - README.md
  - vendor

# Conversion and Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for Collections
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji